version: '3.8'

services:
  # THÊM ĐOẠN NÀY VÀO TRƯỚC BACKEND
  mongodb:
    image: mongo:latest
    container_name: insight_mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - insight-net

  backend:
    build:
      context: ./sources/insight/backend
      dockerfile: Dockerfile
    container_name: insight_backend
    restart: unless-stopped
    depends_on:
      - mongodb # Đợi database chạy xong mới chạy backend
    env_file:
      - ./sources/insight/.env
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    ports:
      - "3003:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - insight-net

  frontend:
    build:
      context: ./sources/insight/frontend
      dockerfile: Dockerfile
    container_name: insight_frontend
    restart: unless-stopped
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - insight-net

networks:
  insight-net:
    driver: bridge

# THÊM ĐOẠN NÀY ĐỂ LƯU DỮ LIỆU DB KHÔNG BỊ MẤT KHI RESTART
volumes:
  mongo-data: